upstream api_gateway_backend {
    server uit-go-project-api-gateway-1:4000;
    server uit-go-project-api-gateway-2:4000;
    server uit-go-project-api-gateway-3:4000;
    # Nhiều instance hơn sẽ thành api-gateway_3, _4...
}

server {
    listen 4000;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_pass http://api_gateway_backend;
    }

    # optional: healthcheck endpoint proxying
    location = /health {
      proxy_pass http://api_gateway_backend/health;
    }
}
